### ISSUE TITLE
Support for osp-core>3.6.0

### ISSUE THREAD

**Issue by razekmh** [simphony/simphony-sqlalchemy#3]
I tried installing the latest master with osp-core 3.8.0 but got this error. 
`Processing dependencies for simphony-sqlalchemy==2.2.1
error: osp-core 3.8.0 is installed but osp-core<3.6.0 is required by {'simphony-sqlalchemy'}`
is there a version of this wrapper that supports osp-core 3.8.0?
linked to [issue 210 in the docs repo](https://github.com/simphony/docs/issues/210)

**Comment by domgz** [comment]
I just published a [new release](https://github.com/simphony/simphony-sqlalchemy/releases/tag/v2.2.2) to solve this. Update the repository via `git pull` or use the [download link](https://github.com/simphony/simphony-sqlalchemy/archive/refs/tags/v2.2.2.zip) from the [release page](https://github.com/simphony/simphony-sqlalchemy/releases/tag/v2.2.2) to get the new version.
